name: Cloudflare KV Update

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  workflow_call:
    inputs:
      variable_value:
        required: true
        type: string
      kv_id:
        required: true
        type: string
      variable_name:
        required: true
        type: string
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  update-kv:
    runs-on: ${{inputs.runs_on}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Update Cloudflare KV
        run: |
          set -e
          curl --fail -X PUT "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/storage/kv/namespaces/${{inputs.kv_id}}/values/${{inputs.variable_name}}" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: text/plain" \
            --data "${{inputs.variable_value}}"
  notify:
    if: always() # Ensures this job runs regardless of the completion status of dependent jobs
    needs:
      - update-kv
    uses: ./.github/workflows/notification.yml
    secrets: inherit
    with:
      job_status: ${{ needs.update-kv.result }}
      workflow: ${{ github.workflow }}
      runs_on: ${{inputs.runs_on}}