name: Cloudflare KV Update

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  workflow_call:
    inputs:
      variable_value:
        required: true
        type: string
      kv_id:
        required: true
        type: string
      variable_name:
        required: true
        type: string
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"

concurrency:
  group: update-bonds-limit
  cancel-in-progress: true

jobs:
  update-kv:
    runs-on: ${{inputs.runs_on}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5

      - name: Update Cloudflare KV
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/storage/kv/namespaces/${{inputs.kv_id}}/values/${{inputs.variable_name}}" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: text/plain" \
            --data "${{inputs.variable_value}}"