name: Firebase CI

permissions:
  id-token: write
  contents: write

on:
  workflow_call:
    inputs:
      FLAVOUR:
        required: false
        type: string
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      send_notifications:
        description: 'Set to true to send Slack notifications'
        required: false
        type: boolean
        default: true
      name:
        description: 'The name of the job'
        required: false
        type: string
        default: 'firebase-ci'
      min_coverage:
        description: 'Minimum required firebase statement coverage percentage'
        required: false
        type: number
        default: 50

jobs:
  ci:
    name: ${{ inputs.name }}
    runs-on: ${{ inputs.runs_on }}
    environment: ${{ inputs.FLAVOUR }}
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: firebase/functions/package-lock.json

      - name: Install Dependencies
        working-directory: firebase/functions
        run: npm ci

      - name: Lint Firebase Functions
        working-directory: firebase/functions
        run: npx tsc --noEmit && npx eslint . --fix

      - name: Run Unit Tests with Coverage
        uses: demian-ilnytskyi/workflows/.github/actions/run-firebase-tests-with-coverage@main
        with:
          min_coverage: ${{ inputs.min_coverage }}
          working_directory: firebase/functions

  notify:
    if: always() && inputs.send_notifications == true
    needs:
      - ci
    uses: ./.github/workflows/notification.yml
    secrets: inherit
    with:
      job_status: ${{ needs.ci.result }}
      workflow: ${{ github.workflow }}
      runs_on: ${{ inputs.runs_on }}
      trigger_actor: ${{ github.actor }}
