name: Firebase Deploy Functions

env:
  GITHUB_OUTPUT: ${{github.workspace}}/.github/workflows/output.txt
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout 

on:
  workflow_call:
    inputs:
      FLAVOUR:
        required: false
        type: string
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      FUNCTIONS:
        required: false
        type: string
        default: ""
      FIREBASE_FUNCTIONS_DIR:
        required: false
        type: string
        default: "functions"
      FORCE_DELETE:
        description: "Force deletion of functions not in local source"
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ${{inputs.runs_on}} # We are using ubuntu to deploy flutter web
    timeout-minutes: 10
    environment: ${{inputs.FLAVOUR}} 
    steps:
    - uses: actions/checkout@v4

    - name: Check required secrets
      uses: demian-ilnytskyi/workflows/.github/actions/check-required-vars@main
      with:
        vars: |
          FIREBASE_TOKEN
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: ${{ inputs.FIREBASE_FUNCTIONS_DIR }}/package-lock.json

    - name: Install dependencies
      working-directory: ${{ inputs.FIREBASE_FUNCTIONS_DIR }}
      run: |
        sudo apt-get update && sudo apt-get install -y expect
        npm install -g firebase-tools
        npm ci

    - name: Deploy Functions
      uses: demian-ilnytskyi/workflows/.github/actions/deploy-firebase-functions@main
      with:
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}
        firebase_project_id: ${{ vars.FIREBASE_PROJECT_ID }}
        force_delete: ${{ inputs.FORCE_DELETE }}
  notify:
    if: always() # Ensures this job runs regardless of the completion status of dependent jobs
    needs:
      - deploy
    uses: ./.github/workflows/notification.yml
    secrets: inherit
    with:
      job_status: ${{ needs.deploy.result }}
      workflow: ${{ github.workflow }}
      runs_on: ${{inputs.runs_on}}
