name: Next JS CI

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"

      working_directory:
        required: false
        type: string
        default: "."
      send_notifications:
        description: 'Set to true to send Slack notifications'
        required: false
        type: boolean
        default: true
      tsconfig_path:
        description: 'Path to the tsconfig.json file'
        required: false
        type: string
        default: 'tsconfig.json'
      eslint_dir:
        description: 'Directory to run ESLint on'
        required: false
        type: string
        default: 'src'
      ignore_patterns:
        description: 'Regex patterns to ignore in the output'
        required: false
        type: string
        default: 'public/images'
      name:
        description: 'The name of the job'
        required: false
        type: string
        default: 'ci'
      min_coverage:
        description: 'Minimum required statement coverage percentage'
        required: false
        type: number
        default: 50
      run_tests:
        description: 'Set to true to run unit tests'
        required: false
        type: boolean
        default: false
      test_path:
        description: 'Path or file pattern to run tests on'
        required: false
        type: string
        default: 'src/__tests__'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  ci:
    name: ${{ inputs.name }}
    runs-on: ${{inputs.runs_on}} # We are using ubuntu to deploy flutter web
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Up Node.js
        uses: actions/setup-node@main
        with:
          node-version: ${{ vars.NODE_FRAMEWORK_VERSION }}
          cache: npm
          cache-dependency-path: ${{ inputs.working_directory }}/package-lock.json

      - name: 📦 Install Dependencies
        # npm ci instead of npm install to not overwrite package_lock.json
        run: npm install

      - name: 🔍 Code Quality Check
        uses: demian-ilnytskyi/workflows/.github/actions/nextjs-code-quality-check@main
        with:
          working_directory: ${{ inputs.working_directory }}
          tsconfig_path: ${{ inputs.tsconfig_path }}
          eslint_dir: ${{ inputs.eslint_dir }}
          ignore_patterns: ${{ inputs.ignore_patterns }}

      - name: 🧪 Run Tests
        if: ${{ inputs.run_tests }}
        uses: demian-ilnytskyi/workflows/.github/actions/run-nextjs-tests-with-coverage@main
        with:
          working_directory: ${{ inputs.working_directory }}
          test_path: ${{ inputs.test_path }}
          min_coverage: ${{ inputs.min_coverage }}
  notify:
    if: always() && inputs.send_notifications == true # Ensures this job runs regardless of the completion status of dependent jobs, but only if notifications are enabled
    needs:
      - ci
    uses: ./.github/workflows/notification.yml
    secrets: inherit
    with:
      job_status: ${{ needs.ci.result }}
      workflow: ${{ github.workflow }}
      runs_on: ${{inputs.runs_on}}
      trigger_actor: ${{ github.actor }}
      pr_title: ${{ github.event.pull_request.title }}
