name: Notify

on:
  workflow_call:
    inputs:
      job_status:
        required: true
        type: string
      workflow:
        required: true
        type: string
      dop_text:
        required: false
        type: string
        default: ""
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      trigger_actor:
        required: false
        type: string
        default: ""
      pr_title:
        required: false
        type: string
        default: ""

jobs:
  notification:
    timeout-minutes: 3
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Prepare Telegram Message
        id: prepare_msg
        uses: demian-ilnytskyi/workflows/.github/actions/prepare-telegram-message@main
        with:
          trigger_actor: ${{ inputs.trigger_actor }}
          pr_title: ${{ inputs.pr_title }}
          workflow_name: ${{ inputs.workflow }}
          job_status: ${{ inputs.job_status }}

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: ${{ steps.prepare_msg.outputs.message }}
