name: CD - Publish Package

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      working_directory:
        required: false
        type: string
        default: "."
      registry_url:
        required: false
        type: string
        default: "https://registry.npmjs.org"
      access:
        required: false
        type: string
        default: "public"

env:
  GITHUB_OUTPUT: ${{github.workspace}}/.github/workflows/output.txt
permissions:
  contents: read

jobs:
  publish:
    runs-on: ${{ inputs.runs_on }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🎯 Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: ${{ vars.NODE_FRAMEWORK_VERSION }}
          registry-url: ${{ inputs.registry_url }}
          cache: npm
          cache-dependency-path: ${{ inputs.working_directory }}/package-lock.json

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🧪 Run Tests
        run: npm test

      - name: 🏗️ Build
        run: npm run build

      - name: 🚀 Publish to npm
        run: npm publish --access ${{ inputs.access }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
